### ISSUE TITLE
Too many unnecessary files.

### ISSUE THREAD

**Issue by satom9to5** [xsota/dotfiles#2]

**Comment by mulleimer** [comment]
not too many, almost all of it

**Comment by satom9to5** [comment]
unnecessary "File"!
nececessary "Directory" only.

**Comment by mulleimer** [comment]
README is the only trustable

**Comment by xsota** [comment]
what do you mean...

**Comment by ghost** [comment]
@satom9to5 your f**kin spell miss HAHAHA

**Comment by mulleimer** [comment]
@satom9to5 *necessary
